ServerName ctflab.local

<VirtualHost *:80>
    ServerAdmin admin@ctflab.local
    DocumentRoot /var/www/html
    ServerName ctflab.local

    DirectoryIndex index.php index.html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Intentionally expose server info for recon
    ServerSignature On

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
